development:
  adapter: postgresql
  database: portal-808-drop
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: portal-808-drop
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: portal-808-drop
  pool: 5
  timeout: 5000
