development:
  secret_key_base: <%= ENV['SECRET_BASE'] %>
  twilio_account_sid:  <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_SID'] %>
  twilio_phone_number: <%= ENV['TWILIO_PHONE_NUMBER'] %>

production:
  secret_key_base: <%= ENV['SECRET_BASE'] %>
  twilio_account_sid:  <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_SID'] %>
  twilio_phone_number: <%= ENV['TWILIO_PHONE_NUMBER'] %>